language: ruby
cache: bundler
bundler_args: --without production

rvm:
 - 2.7.0
 
before_install:
 - gem install bundler:2.2.11

script:
 - bundle exec rspec


deploy:
 provider: heroku
 api_key: dd833edc-e6b2-43a0-9a6a-fc12011bb436
 app: calm-plateau-14847
 run heroku: "rake db:migrate"
 on:
  all_branches: true